### PR TITLE
add drop sound

### PR DESCRIPTION
**Pull request by oh3vci**
I added a drop sound to make the blocks feel more realistic.

### CODE REVIEW

**Review by WoochanLee — CHANGES_REQUESTED** [review]
I think that this sound is too small and unsuitable to drop block.
Could you find another sound effect?
Thanks for your assistance!

**Comment by oh3vci** [comment]
ok... I will find another one

**Comment by WoochanLee** [comment]
Oh LGTM!
Thanks!

**Review by WoochanLee — APPROVED** [review]

**Comment by WoochanLee** [comment]
I will publish this in a few minutes!

**Pull request merged**
