### PR TITLE
Add the shift sound and some meta properties

### PR DESCRIPTION
**Pull request by oh3vci**

### CODE REVIEW

**Comment by WoochanLee** [comment]
Thanks for PR!
Please add a description for review~!

**Comment by oh3vci** [comment]
There is no description because of the commit log shows all of things.

**Comment by WoochanLee** [comment]
Yes, right. But I think add a description is better for PR.
Please add next time.

**Comment by WoochanLee** [comment]
And It is definitely better than no sound. But is there any better sound? The sound seems to be a little small.

**Comment by oh3vci** [comment]
> And It is definitely better than no sound. But is there any better sound? The sound seems to be a little small.

I changed it

**Pull request merged**
